Improve Intel hardware checks (#12)
* Improve Intel hardware detection

* Do not match on word

* Extend PATH for intel_gpu_top and fix var reference

* Switch order for better user experience

* Improve returns and enable nullglob

* Suppress warning for systems not containing Intel CPU

diff --git a/command-chain/openvino-launch b/command-chain/openvino-launch
--- a/command-chain/openvino-launch
+++ b/command-chain/openvino-launch
@@ -8,46 +8,58 @@
 #
 
 CONTENT_PATH="${SNAP}/openvino"
-if [ ! -d "${CONTENT_PATH}" ]; then
-  echo "Warning: ${CONTENT_PATH} not present inside ${SNAP_NAME} snap. Please connect the content interface at this path."
+if [ ! -d "${CONTENT_PATH}" ] && grep -qw "GenuineIntel" /proc/cpuinfo; then
+  echo "Warning: ${CONTENT_PATH} not present inside ${SNAP_NAME} snap. Please install the snap using 'sudo snap install openvino-toolkit-2404 --beta' and restart the application."
 fi
 export LD_LIBRARY_PATH="${SNAP}/openvino/usr/lib/$(uname -m)-linux-gnu":$LD_LIBRARY_PATH
 export PYTHONPATH="${SNAP}/openvino/usr/lib/python3/dist-packages":$PYTHONPATH
+export PATH="${SNAP}/openvino/usr/bin":$PATH
+
+# Check if device node is an Intel GPU
+node_is_intel_gpu() {
+  node=$1
+  render_device_name=$(echo "${node}" | cut -f4 -d"/") # e.g. renderD128
+  gpu_info=$(intel_gpu_top -L | grep -B1 -w "${render_device_name}")
+  if echo "${gpu_info}" | grep -qw "pci:vendor=8086"; then
+    return 0 # this node is an Intel GPU
+  fi
+  return 1 # not an Intel GPU
+}
 
 # Check user access to Intel accelerator devices (GPU and NPU)
 check_user_access() {
-  if [ $# -ne 3 ]; then
-    echo "Unable to check user access to device accelerator(s)."
-    return 0
-  fi
-  device_type=$1
-  glob_path=$2 # /dev/dri/card, /dev/dri/render, or /dev/accel/accel
-  required_group=$3
-
-  if ! compgen -G "${glob_path}"* > /dev/null; then
-    return 0 # skip as there is no device on the host
-  fi
-
-  if ! id -nGz "${USER}" | grep -qzxF "${required_group}"; then
-    echo "Warning: to use the ${device_type} plugin, the user must be in the ${required_group} group."
-    echo "Please run 'sudo usermod -a -G ${required_group} ${USER}' then log out and back in."
-    return 0
-  fi
-
-  for node in "${glob_path}"*; do
-    if ! test -r "${node}" || ! test -w "${node}"; then
-      echo "Warning: to use device ${node} with the ${device_type} plugin, the user must have read and write access to ${node}."
-      echo "Please run 'sudo chown root:${required_group} ${node} && sudo chmod g+rw ${node}'."
-      echo "Also confirm (run 'snap connections') that snap interfaces required to access ${node} are connected."
-      return 0
+  node=$1
+  if echo "${node}" | grep -q render; then
+    if ! node_is_intel_gpu "${node}"; then
+      return # non-Intel GPUs unsupported
     fi
-  done
+    device_type="GPU"
+  else
+    device_type="NPU"
+  fi
+
+  if ! id -nGz "${USER}" | grep -qzxF render; then
+    echo "Warning: to use the ${device_type} plugin, the user must be in the render group."
+    echo "Please run 'sudo usermod -a -G render ${USER}' then log out and back in."
+    return
+  fi
+
+  if ! test -r "${node}" || ! test -w "${node}"; then
+    echo "Warning: to use device ${node} with the ${device_type} plugin, the user must have read and write access to ${node}."
+    echo "Please run 'sudo chown root:render ${node} && sudo chmod g+rw ${node}'."
+    echo "Also confirm (run 'snap connections') that snap interfaces required to access ${node} are connected."
+    return
+  fi
 }
 
-# OpenVINO only supports Intel GPU and NPU for acceleration
-if [ "$(uname -m)" = "x86_64" ]; then
-  check_user_access GPU /dev/dri/render render
-  check_user_access NPU /dev/accel/accel render
-fi
+# handle cases where no render or accel nodes present
+shopt -s nullglob
+
+for node in /dev/dri/render*; do
+  check_user_access "${node}"
+done
+for node in /dev/accel/accel*; do
+  check_user_access "${node}"
+done
 
 exec "$@"
